import = ["/Users/majestic/.config/alacritty/themes/dracula/dracula.toml"]

[scrolling]
history = 10000
multiplier = 3

[window]
opacity = 0.65
blur = true

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 5
y = 5

[font]
size = 17.0

[font.normal]
family = "CodeNewRoman Nerd Font Mono"

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[shell]
program = "/opt/homebrew/bin/tmux"

